### ISSUE TITLE
Question: can I preload a static map in slam2d?

### ISSUE THREAD

**Issue by zouyonghao** [iris-ua/iris_lama_ros#20]
It is useful for me when I want to load a unfinished static map and continue to build it.

**Comment by eupedrosa** [comment]
Right now, it is not possible. The read/write of maps is (almost) implemented but not tested, therefore it is not exposed.

**Comment by zouyonghao** [comment]
I use `setOccupied` just like loc_2d to implement it, it seems good for me.

**Comment by Combinacijus** [comment]
> Right now, it is not possible. The read/write of maps is (almost) implemented but not tested, therefore it is not exposed.

@eupedrosa I would also like to preload a static map in slam2d. Is this feature already exposed because I couldn't find it?

**Comment by eupedrosa** [comment]
This feature is not yet available.
