### ISSUE TITLE
No map publish when use with real hardware

### ISSUE THREAD

**Issue by IST-DEV20** [iris-ua/iris_lama_ros#40]
How to fix this no map publish when use with real hardware? (can be used with gazebo)

**Comment by jcmonteiro** [comment]
@IST-DEV20, this is likely a problem in your setup. Check if the lidars are published to the correct topic and with data and also if you have your `base_link` to `odom` tf being updated as you move the robot.

**Comment by IST-DEV20** [comment]
@jcmonteiro, topic and data is look good but when I launch /slam2d_ros I can't echo tf between `base_link` to `odom`
my tf tree
![Screenshot from 2021-06-15 14-12-09](https://user-images.githubusercontent.com/69836692/122009083-ee0c8400-cde3-11eb-8804-ea521f6d097b.png)
my /scan topic
![Screenshot from 2021-06-15 14-11-12](https://user-images.githubusercontent.com/69836692/122009235-11cfca00-cde4-11eb-8e6a-cc657dfae70c.png)
![Screenshot from 2021-06-15 14-11-25](https://user-images.githubusercontent.com/69836692/122009243-14322400-cde4-11eb-85f3-22193c5beeef.png)

**Comment by jcmonteiro** [comment]
Could you share your roslaunch configuration and the rosnode graph?

**Comment by IST-DEV20** [comment]
@jcmonteiro this is my launch of `slam2d_ros.launch`
`
<?xml version="1.0"?>
<launch>
    <arg name="scan_topic" default="/scan"/>
    <arg name="rosbag" />

    <arg name="particles" default="30"/>
    <arg name="d_thresh"  default="0.5"/>
    <arg name="a_thresh"  default="0.5"/>
    <arg name="mrange"    default="20"/>

    <arg name="threads"   default="4"/>
    <arg name="use_compression" default="false"/>

    <param name="/use_sim_time" value="true"/>

    <node pkg="iris_lama_ros" name="slam2d_ros" type="slam2d_ros" output="screen" >
        <param name="scan_topic" value="$(arg scan_topic)"/>
        

        <param name="d_thresh"  value="$(arg d_thresh)"/>
        <param name="a_thresh"  value="$(arg a_thresh)"/>
        <param name="mrange"    value="$(arg mrange)"/>

        <param name="use_compression" value="$(arg use_compression)"/>

        <param name="create_summary"     value="true"/>
        <param name="map_publish_period" value="0.01" />
    </node>
</launch>`

and node graph same this https://github.com/iris-ua/iris_lama_ros/issues/40#issuecomment-861245936

**Comment by jcmonteiro** [comment]
Is the `scan_topic` defined somewhere else?

**Comment by IST-DEV20** [comment]
`  <?xml version="1.0"?>
<launch>

    <arg name="scan_topic" default="/scan"/>
    <arg name="rosbag" />
    <arg name="particles" default="30"/>
    <arg name="d_thresh"  default="0.5"/>
    <arg name="a_thresh"  default="0.5"/>
    <arg name="mrange"    default="20"/>

    <arg name="threads"   default="4"/>
    <arg name="use_compression" default="false"/>

    <param name="/use_sim_time" value="true"/>

    <node pkg="iris_lama_ros" name="slam2d_ros" type="slam2d_ros" output="screen" >
        <param name="scan_topic" value="$(arg scan_topic)"/>
        

        <param name="d_thresh"  value="$(arg d_thresh)"/>
        <param name="a_thresh"  value="$(arg a_thresh)"/>
        <param name="mrange"    value="$(arg mrange)"/>

        <param name="use_compression" value="$(arg use_compression)"/>

        <param name="create_summary"     value="true"/>
        <param name="map_publish_period" value="0.01" />
    </node>
</launch>
`

**Comment by jcmonteiro** [comment]
And are you changing the topic by passing the argument to the launch? Are you really publishing to `/scan`?

**Comment by IST-DEV20** [comment]
@jcmonteiro, Sorry for reply rate. Update I fixed problem by set parameter  `/use_sim_time` to `false` cause when I launch with  real hardware and set `/use_sim_time` to `true` no topic sim_time. 

Thank you for your help and support

**Comment by jcmonteiro** [comment]
Ooh, missed that one in your launch file. In practice, you should avoid `use_sim_time` in "inner" launch files and have it only in a top-level launch that calls for the others.
