### ISSUE TITLE
Large TF delay in odom to map transform

### ISSUE THREAD

**Issue by JordySehn** [iris-ua/iris_lama_ros#42]
First of all, great package!

So far (in simulation) I am getting very good localization results compared to amcl on our robot.

I did notice though that the transform delay from the odom to map transform seems unusually high to me? Using tf_monitor I get about 0.4 seconds average delay from odom -> map.

In contrast, amcl seems to only have a delay of about 0.1 seconds or so. Any idea why this would be? Have other people noticed similar transform delays?

**Comment by JordySehn** [comment]
ahh you know what, the problem was just the transform tolerance parameter was set too low for me.

Bumping it up a tad brought the delay way down. Thanks!

**Comment by eupedrosa** [comment]
Glad I could help :smile:

**Comment by Combinacijus** [comment]
TF delay could also happen if you built from source in with a Debug flag it's drastically slower than using [Release flag](https://answers.ros.org/question/311472/how-to-build-release-version-of-ros-node/)
