### ISSUE TITLE
Galactic support

### ISSUE THREAD

**Issue by robvoi** [iris-ua/iris_lama_ros#50]
Is this node supported on galactic and the current nav2 version?

**Comment by eupedrosa** [comment]
Hello @robvoi.

At the moment ROS2 is not supported. It will be in the future, but not right now. There is a branch for `dashing` and `eloquent` but they are not currently maintained.

LaMa is independent of ROS, so you can create your own port if you have the time to spare.

**Comment by robvoi** [comment]
Thanks a lot.
Would really be curious too see it in action.

Time is one thing. Capability the other.  :-) 

> Hello @robvoi.
> 
> At the moment ROS2 is not supported. It will be in the future, but not right now. There is a branch for `dashing` and `eloquent` but they are not currently maintained.
> 
> LaMa is independent of ROS, so you can create your own port if you have the time to spare.
