### ISSUE TITLE
How to cite this method?

### ISSUE THREAD

**Issue by josematez** [iris-ua/iris_lama_ros#54]
Hi, I am interested in using the localization method in my research, but I need an article where the method is described in order to cite it correctly. I have found one titled "Efficient localization based on scan matching with a continuous likelihood field" by Eurico Pedrosa et al, published in ICARSC 2017, but I am not sure if the method described in that paper is the same one implemented here or if the method is published in another paper. Can someone clarify it for me?

**Comment by eupedrosa** [comment]
Hi @josematez.

The method described in the "Efficient localization based on scan matching with a continuous likelihood field" article is the one that is implemented.

There is a few additions to the implementation such as the covariance calculation that comes from the article “Real-time correlative scan matching” by E. B. Olson,  but the core localization algorithm is still the same.
