### ISSUE TITLE
new lidar odom compiler error

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [iris-ua/iris_lama_ros#57]
Errors     << iris_lama_ros:make /home/jason/loc_ws/logs/iris_lama_ros/build.make.005.log                                                                                                                                                                                        
In file included from /home/jason/loc_ws/devel/include/lama/lidar_odometry_2d.h:36:0,
                 from /home/jason/loc_ws/src/iris_lama_ros/include/lama/ros/lidar_odometry2d_ros.h:55,
                 from /home/jason/loc_ws/src/iris_lama_ros/src/lidar_odometry2d_ros.cpp:37:
/home/jason/loc_ws/devel/include/lama/types.h:101:27: error: redefinition of ‘template<class T> int lama::sign(T)’
 template <typename T> int sign(T val) {
                           ^~~~
In file included from /opt/ros/melodic/include/lama/image.h:38:0,
                 from /home/jason/loc_ws/src/iris_lama_ros/src/lidar_odometry2d_ros.cpp:34:
/opt/ros/melodic/include/lama/types.h:89:27: note: ‘template<class T> int lama::sign(T)’ previously declared here
 template <typename T> int sign(T val) {
                           ^~~~
In file included from /home/jason/loc_ws/devel/include/lama/lidar_odometry_2d.h:36:0,
                 from /home/jason/loc_ws/src/iris_lama_ros/include/lama/ros/lidar_odometry2d_ros.h:55,
                 from /home/jason/loc_ws/src/iris_lama_ros/src/lidar_odometry2d_ros.cpp:37:
/home/jason/loc_ws/devel/include/lama/types.h:105:8: error: redefinition of ‘struct lama::KeyHash’
 struct KeyHash {
        ^~~~~~~
In file included from /opt/ros/melodic/include/lama/image.h:38:0,
                 from /home/jason/loc_ws/src/iris_lama_ros/src/lidar_odometry2d_ros.cpp:34:
/opt/ros/melodic/include/lama/types.h:93:8: note: previous definition of ‘struct lama::KeyHash’
 struct KeyHash {
        ^~~~~~~
In file included from /home/jason/loc_ws/devel/include/lama/lidar_odometry_2d.h:36:0,
                 from /home/jason/loc_ws/src/iris_lama_ros/include/lama/ros/lidar_odometry2d_ros.h:55,
                 from /home/jason/loc_ws/src/iris_lama_ros/src/lidar_odometry2d_ros.cpp:37:
/home/jason/loc_ws/devel/include/lama/types.h:111:8: error: redefinition of ‘struct lama::PointCloudXYZ’
 struct PointCloudXYZ {
        ^~~~~~~~~~~~~
In file included from /opt/ros/melodic/include/lama/image.h:38:0,
                 from /home/jason/loc_ws/src/iris_lama_ros/src/lidar_odometry2d_ros.cpp:34:
/opt/ros/melodic/include/lama/types.h:99:8: note: previous definition of ‘struct lama::PointCloudXYZ’
 struct PointCloudXYZ {
        ^~~~~~~~~~~~~
In file included from /home/jason/loc_ws/devel/include/lama/lidar_odometry_2d.h:36:0,
                 from /home/jason/loc_ws/src/iris_lama_ros/include/lama/ros/lidar_odometry2d_ros.h:55,
                 from /home/jason/loc_ws/src/iris_lama_ros/src/lidar_odometry2d_ros.cpp:37:
/home/jason/loc_ws/devel/include/lama/types.h:122:8: error: redefinition of ‘struct lama::PolygonMesh’
 struct PolygonMesh {
        ^~~~~~~~~~~
In file included from /opt/ros/melodic/include/lama/image.h:38:0,
                 from /home/jason/loc_ws/src/iris_lama_ros/src/lidar_odometry2d_ros.cpp:34:
/opt/ros/melodic/include/lama/types.h:110:8: note: previous definition of ‘struct lama::PolygonMesh’
 struct PolygonMesh {
        ^~~~~~~~~~~
make[2]: *** [src/CMakeFiles/lidar_odometry2d_ros.dir/lidar_odometry2d_ros.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/lidar_odometry2d_ros.dir/all] Error 2

**Comment by ZOUJIASHUAI** [comment]
@eupedrosa please help

**Comment by eupedrosa** [comment]
Are you also using the most recent version of [iris_lama](github.com/iris-ua/iris_lama) ?

**Comment by ZOUJIASHUAI** [comment]
> Are you also using the most recent version of [iris_lama](github.com/iris-ua/iris_lama) ?

yes i did

**Comment by ZOUJIASHUAI** [comment]
@eupedrosa can you compile iris lama & iris lama ros success?

**Comment by eupedrosa** [comment]
Yes, it compiles. However, I only tested with ROS Noetic. Are you using a different distro?

**Comment by ZOUJIASHUAI** [comment]
> Yes, it compiles. However, I only tested with ROS Noetic. Are you using a different distro?
@eupedrosa 
 I compiles with melodic，I will test it on Noetic

**Comment by ZOUJIASHUAI** [comment]
hello @eupedrosa 
I compiled iris lama success on noetic,but failed on melodic ,can you try to make it work on melodic,then I can test it on factory

**Comment by eupedrosa** [comment]
I did a fresh installation with melodic and it compiled. Are you using ubuntu 18.04?
I am not able to replicate your problem.

**Comment by ZOUJIASHUAI** [comment]
> I did a fresh installation with melodic and it compiled. Are you using ubuntu 18.04? I am not able to replicate your problem.

@eupedrosa  I used another computer with melodic and it complied success ,maybe my labtop has some environment peoblem
