### ISSUE TITLE
How can iris_lama be automatically linked with ROS2 'colcon' tool?

### ISSUE THREAD

**Issue by bluemoon93** [iris-ua/iris_lama_ros#7]
How can the `iris_lama` package be automatically linked, when using `colcon` to build the ROS2 port of `iris_lama_ros`? 

My current approach is to copy header files into the `include/lama` folder, and building `iris_lama.a` to put into the src directory. This works, but is not very portable. Is there a way to automate this, and build both packages automatically? [This](https://index.ros.org//doc/ros2/Tutorials/Ament-CMake-Documentation/) has some information about exporting a package, but I was unable to get it working.

**Comment by eupedrosa** [comment]
What is the output of the error?

**Comment by bluemoon93** [comment]
There isn't an error, I fixed all linkage errors by building `iris_lama` separately with `cmake` and 
  
    cp iris_lama/build/src/libiris_lama.a dev_ws/src/iris_lama_ros
    cp -r iris_lama/include dev_ws/src/iris_lama_ros/

If I don't copy the header `.h` files manually, when compiling I get

    fatal error: lama/slam2d.h: No such file or directory

And if I don't copy the binary `libiris_lama.a` manually, I get 

    No rule to make target '/mnt/myfolder/dev_ws/src/iris_lama_ros/libiris_lama.a', needed by 'src/loc2d_ros'

I think there are ways of automating this and, when building `iris_lama` with catkin, making it available to colcon? If not, the documentation includes all these steps. It's just not as elegant,

**Comment by eupedrosa** [comment]
Yes, it is not elegant. I will try to find a fix.

**Comment by eupedrosa** [comment]
@bluemoon93, I think I solved it. I made some changes to the packages to make it work. I am going to push the changes. With this push it will no longer be necessary to do the manual copies. Nonetheless, can you also verify that it is working? Remember to pull the changes from `iris_lama` before testing.

**Comment by CleopatraDion** [comment]
Just as some input. I pulled the eloquent-devel branch to build it again, following the instructions and I was getting some linkage errors. Then I found this issue and built iris_lama with colcon, and then iris_lama_ros, as per your new method and it was fine. So, instructions will prob have to be updated. I will be happy to help out with updating instructions and things like that once I get a bit more used to the package.

**Comment by eupedrosa** [comment]
Hi, @CleopatraDion.

> I will be happy to help out with updating instructions and things like that once I get a bit more used to the package.

That would be great. I did not update the instructions because I was waiting for feedback. If it works fine and you are willing to do the necessary changes to the documentation, just do a pull request and I will accept it.

**Comment by bluemoon93** [comment]
Confirmed this worked on both branches. I've updated docs and am closing the issue
