### ISSUE TITLE
Message Filter dropping message: frame 'scan' at time ... for reason 'Unknown'

### ISSUE THREAD

**Issue by CleopatraDion** [iris-ua/iris_lama_ros#9]
@bluemoon93  This issue happens when i launch both live methods. Again using ubuntu 18.06 & eloquent. I'm publishing valid data to both the /scan and /odom topics...

**Comment by bluemoon93** [comment]
How are the data being published to the `scan` topic?

I recommend checking out the `dashing-devel` branch, it's the one I ran tests on. It works with TurtleBot3 simulation and includes a handy `start.sh` help file with useful commands (alongside the `README` with instructions).
